site_url: https://pujanmotiwala.github.io/my-data-science-notes/

site_name: My Data Science Notes
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.svg # Path relative to the 'docs' directory
  favicon: assets/logo.svg # Optional: Add a favicon too
  palette:
    # Palette toggle for dark mode
    - scheme: slate  # 'slate' is the dark scheme
      primary: blue   # Choose a primary color for dark mode
      accent: light-blue # Choose an accent color for dark mode
      toggle:
        icon: material/brightness-4 # Icon for switching TO dark mode (moon)
        name: Switch to dark modes
    # Palette toggle for light mode
    - scheme: default # 'default' is the light scheme
      primary: indigo # Choose a primary color (e.g., blue, teal, indigo)
      accent: blue    # Choose an accent color
      toggle:
        icon: material/brightness-7 # Icon for switching TO light mode (sun)
        name: Switch to light mode
  features:
    - navigation.tabs # Use tabs for top-level sections if you like
    - navigation.sections # Expand sections in sidebar
    - navigation.expand # Expand all sections in sidebar
    - navigation.instant # Instant loading of pages
    - navigation.top # Add a "back to top" button
    - navigation.tracking # Track page views
    - navigation.indexes # Add index pages for sections
    - navigation.search # Add search functionality
    - navigation.search.highlight # Highlight search terms in search results
    - navigation.search.suggest # Autocomplete in search
    - navigation.path # Show paths in sidebar  
    - toc.integrate # Move Table of Contents into sidebar
    - search.suggest # Autocomplete in search
    - search.highlight # Highlight search terms
    - content.code.annotate # Allow code annotations
    - content.code.copy # Add copy button to code blocks
# Optional: Add extensions for better Markdown rendering
extra:
  analytics:
    provider: google
    property: G-K08G66LHC7
nav:
  # 1. The Home Page (required)
  - 'Home': 'index.md'

  # 2. Core Concepts / Basics
  - 'The Basics':
      - 'Overview': '01 The Basics/index.md' # Suggest creating this file!
      - Introduction: '01 The Basics/intro.md' # Maybe combine What is DS/ML here
      - Types of Machine Learning: '01 The Basics/ml-types.md'
      - The Workflow: '01 The Basics/ds-ml-workflow.md'
      - Exploratory Data Analysis (EDA): '01 The Basics/intro-to-eda.md'
      - Understanding Data: '01 The Basics/data-types-overview.md'
      - Common Tools: '01 The Basics/common-ds-tools.md'
      - Ethics and Bias: '01 The Basics/data-ethics-bias-intro.md'
      - Glossary: '01 The Basics/stats-ml-glossary.md' # Keep the detailed definitions here

  # 3. Foundational Math
  - 'Mathematics':
      - 'Overview': '02 Math/index.md'
      - 'Probability Theory': '02 Math/01 Probability/index.md'
      - 'Inferential Statistics': '02 Math/02 Inferential statistics/index.md'
      - 'Linear Algebra': '02 Math/03 Linear Algebra/index.md'
      - 'Calculus': '02 Math/04 Calculus/index.md'
      - 'Information Theory': '02 Math/05 Information Theory/index.md'
  # 4. Data Handling Workflow
  - 'Data Collection':
      - 'Overview': '03 Data Collection/index.md'
      - 'Data Types':
          - 'Categorical': '03 Data Collection/Data Types/Categorical (Qualitative data).md'
          - 'Numeric': '03 Data Collection/Data Types/Numeric (Quantitative data).md'
      - 'Populations & Samples': '03 Data Collection/Populations & samples/Population & Sample.md'
      - 'Sampling Methods': '03 Data Collection/Populations & samples/Sampling Methods.md'

  - 'Feature Engineering':
      - 'Introduction': '04 Feature Engineering/index.md'
      - 'Encoding': '04 Feature Engineering/Encoding/Encoding.md'
      # - 'Scaling': '04 Feature Engineering/Scaling_Methods.md' # Add when content exists
      # - 'Feature Creation': '04 Feature Engineering/Creating_Features.md' # Add when content exists

  - 'Data Visualization':
      - 'Principles': '05 Data Visualization/index.md'
      # - 'Matplotlib': '05 Data Visualization/Matplotlib_Guide.md' # Add when content exists
      # - 'Seaborn': '05 Data Visualization/Seaborn_Examples.md' # Add when content exists

  # 5. Modeling Techniques
  - 'Machine Learning':
      - 'Overview': '06 Machine Learning/index.md'
      - 'ML Basics':
          - 'Model Selection': '06 Machine Learning/01 The Basics/01_Model Selection/Model Selection.md'
          - 'Ensemble Methods': '06 Machine Learning/01 The Basics/01_Model Selection/Ensemble/Ensemble.md'
          - 'Model Evaluation': '06 Machine Learning/01 The Basics/02_Model Evaluation/Model Evaluation.md'
          - 'Performance Metrics': '06 Machine Learning/01 The Basics/02_Model Evaluation/Test metrics/Performance Metrics/Performance Metrics.md'
          - 'Regularization': '06 Machine Learning/01 The Basics/02_Model Evaluation/Test metrics/Regularization/Regularization.md'
          - 'Parameter Tuning Intro': '06 Machine Learning/01 The Basics/03_Parameter Tuning/01_Optimizers Intro.md'
          - 'Resampling (Cross-Val)': '06 Machine Learning/01 The Basics/Resampling Method/k-fold cross-validation.md'
      - 'Supervised Learning':
          - 'Overview': '06 Machine Learning/02 Supervised/Supervised.md'
          - 'Regression': '06 Machine Learning/02 Supervised/01 Regression/Regression.md'
          - 'Classification': '06 Machine Learning/02 Supervised/02 Classification/Classification.md'
      - 'Unsupervised Learning':
          - 'Overview': '06 Machine Learning/03 Unsupervised/Unsupervised.md'
          - 'Clustering': '06 Machine Learning/03 Unsupervised/01_Clustering/Clustering.md'
          - 'Dimensionality Reduction': '06 Machine Learning/03 Unsupervised/02_Dimensionality Reduction/Dimensionality Reduction.md'
          - 'Association Rules': '06 Machine Learning/03 Unsupervised/03_Association Rule/Association Rules.md'
      # - 'Semi-supervised Learning': '06 Machine Learning/04 Semi-supervised/...' # Add when content exists
      - 'A/B Testing': '06 Machine Learning/AB Testing/Intro.md'
      - 'Causal Inference': '06 Machine Learning/Causal Inference Methods/Intro.md'
      - 'ML Deployment': '06 Machine Learning/ML Deployment/index.md' # Assumes index.md exists or will be created

  - 'Deep Learning':
      - 'Introduction': '07 Deep Learning/index.md'
      - 'Foundational Models':
          - 'Neural Networks Basics': '07 Deep Learning/01 Foundational Models/Neural Networks/01 The Basics/01_Introduction.md'
          # Link main model files or index files for model sections
          - 'CNNs': '07 Deep Learning/01 Foundational Models/Neural Networks/02 CNN/index.md' # Assumes index.md
          - 'RNNs': '07 Deep Learning/01 Foundational Models/Neural Networks/03 RNN/index.md' # Assumes index.md
          - 'LSTMs': '07 Deep Learning/01 Foundational Models/Neural Networks/04 LSTM/index.md' # Assumes index.md
          - 'Transformers': '07 Deep Learning/01 Foundational Models/Neural Networks/05 Transformer/Transformer Networks.md'
          - 'GANs': '07 Deep Learning/01 Foundational Models/Neural Networks/06 GANs/Generative Adversarial Networks (GAN).md'
          - 'VAEs': '07 Deep Learning/01 Foundational Models/Neural Networks/07 VAE/Autoencoders and Variational Autoencoders (VAE).md'
      - 'Advanced Techniques':
          - 'Data Preparation': '07 Deep Learning/02 Advanced Techniques/01 Data Preparation/index.md' # Assumes index.md
          - 'Training Techniques': '07 Deep Learning/02 Advanced Techniques/02 Training Techniques/index.md' # Assumes index.md
          - 'Evaluation & Validation': '07 Deep Learning/02 Advanced Techniques/03 Model Evaluation & Validation/index.md' # Assumes index.md
          - 'Special Topics': '07 Deep Learning/02 Advanced Techniques/04 Special Topics/index.md' # Assumes index.md (covers Attention, RAG, PEFT etc.)
      - 'Frameworks':
          # Link directly to framework files if they are main content
          - 'PyTorch': '07 Deep Learning/03 Frameworks and Libraries/PyTorch.md'
          - 'TensorFlow': '07 Deep Learning/03 Frameworks and Libraries/TensorFlow.md'
          - 'Keras': '07 Deep Learning/03 Frameworks and Libraries/Keras.md'
          - 'JAX': '07 Deep Learning/03 Frameworks and Libraries/JAX.md'
          - 'Tensors': '07 Deep Learning/03 Frameworks and Libraries/Tensor.md'
      - 'Practical Applications':
          - 'Deployment & MLOps': '07 Deep Learning/04 Practical Applications/Deployment/03 MLOps.md' # Link main concept
          - 'Fine Tuning': '07 Deep Learning/04 Practical Applications/fine_tune_101/Untitled.md' # Link main note
          - 'Industry Use Cases': '07 Deep Learning/04 Practical Applications/Industry Use Cases/index.md' # Assumes index.md

  # 6. Tools and Technologies
  - 'Big Data Technologies':
      - 'Concepts': '08 Big Data Technologies/index.md'
      # - 'Spark': '08 Big Data Technologies/Apache_Spark_Intro.md' # Add when content exists
      # - 'Hadoop': '08 Big Data Technologies/Hadoop_Ecosystem.md' # Add when content exists

  # 7. Important Considerations
  - 'Ethics and Bias':
      - 'Overview': '09 Ethics and Bias/index.md'
      # - 'Fairness': '09 Ethics and Bias/Fairness_Metrics.md' # Add when content exists
      # - 'Privacy': '09 Ethics and Bias/Privacy_Concerns.md' # Add when content exists
      # - 'Explainability': '09 Ethics and Bias/Explainability.md' # Add when content exists

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span # Needed for line highlighting
      pygments_lang_class: true # Usually good practice
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid # If you plan to use Mermaid diagrams directly (Kroki handles this too)
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - toc:
      permalink: true
      toc_depth: 3 # Optional: control how many levels show in TOC
  - pymdownx.tasklist: # For checklists like - [ ] and - [x]
      custom_checkbox: true # Makes them look like actual checkboxes
  - footnotes # For [^1] style footnotes
  - pymdownx.arithmatex: # For LaTeX Math using MathJax ($...$ and $$...$$)
      generic: true # Important setting for Material theme
  - pymdownx.details # For collapsible <details>/<summary> blocks (alternative to admonitions)
  - pymdownx.emoji: # For :emoji: codes
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.magiclink # Auto-links URLs and emails
  - pymdownx.smartsymbols # Converts --- to em-dash, -- to en-dash, ... to ellipsis etc.
  - pymdownx.tabbed: # Create tabbed content sections
      alternate_style: true
  - attr_list # Allows adding HTML attributes/CSS classes to Markdown elements (e.g., {#id .class})
  - md_in_html # Allow processing Markdown syntax inside HTML blocks
  - tables # For GFM style tables (often included by default with Material, but explicit is fine)
  - def_list # For definition lists
  - abbr # For abbreviations
plugins:
  - search # Built-in search plugin, often enabled by default with Material
  - kroki:
      EnableExcalidraw: true
      ServerURL: https://kroki.io  # Default Kroki server
      FileTypes:
        - svg # Add the plugin name here
  - roamlinks
  - exclude:
      glob:
        - 'Excalidraw/**' # Exclude this folder from the build
extra_javascript:
  - javascripts/mathjax.js # Create this file if needed (see below)
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js